### ISSUE TITLE
Sub 1gwei TX Gasprice options or Mwei Options

### ISSUE THREAD

**Issue by marczeller** [MyCryptoHQ/mycrypto.com#25]
Hi,

it's quite not user-friendly right now to make sub-1gwei Tx on Mycrypto.com, can we change that ?
Maybe a custom gasprice box ? or a Mwei/Kwei (in the future) option?

**Comment by MrLuit** [comment]
It's planned for the upcoming MyCrypto beta (v4), but it likely won't be added in v3

**Comment by hahnmichaelf** [comment]
Hey @marczeller , MyCrypto functionality doesn't currently support this, but you can change this by following this gif (https://i.imgur.com/iuzTZYe.gifv), and instead of changing the 'max' field to 1000, change the 'min' field to 0.1 and the 'step' field to 0.1 . This will allow you to set sub-1gwei transactions. Its also important to note here that most miners don't accept sub-1gwei transactions, so you may be waiting for a little bit.

**Comment by tayvano** [comment]
We are reducing the minimum to 0.1 GWEI on the release today. However, the experience is generally much better on https://beta.mycrypto.com/and gives you the control you are seeking. :)
